micronaut:
  application:
    name: gallerySharer
  security:
    authentication: session
    redirect:
      unauthorized.url: /login # default is / and how will you log in?
      prior-to-login: true # redirect user back to page they wanted

    # simply using defaults here:
    #endpoints:
    #  login:
    #    enabled: true
    #    path: /login

  server:
    port: 8081

  router:
    static-resources:
      default:
        paths:
          - classpath:/public

datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    driverClassName: org.h2.Driver
    schema-generate: NONE
    dialect: H2

netty:
  default:
    allocator:
      max-order: 3
